'use strict';
(() => {
const KEY='hamster-little-home-v1', VERSION=1;
const $=s=>document.querySelector(s), clamp=(n,a=0,b=100)=>Math.max(a,Math.min(b,n)), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const TYPES={cream:{name:'奶油金丝熊',desc:'软乎乎的小太阳',fur:'#ddb384',light:'#f8e7c7',ear:'#e6b8a9'},gray:{name:'灰白小仓鼠',desc:'安静的温柔伙伴',fur:'#b3b0aa',light:'#f0eae0',ear:'#dfb8b1'},pudding:{name:'布丁小仓鼠',desc:'甜甜的快乐小团子',fur:'#e6c27e',light:'#fff1d3',ear:'#e9bdb0'}};
const FOODS={seed:{name:'瓜子',icon:'🌻',price:3,hunger:12,mood:1,desc:'饱食 +12 · 心情 +1'},carrot:{name:'胡萝卜',icon:'🥕',price:5,hunger:18,mood:2,desc:'饱食 +18 · 心情 +2'},apple:{name:'苹果',icon:'🍎',price:6,hunger:15,mood:5,desc:'饱食 +15 · 心情 +5'},cookie:{name:'小饼干',icon:'🍪',price:8,hunger:10,mood:10,desc:'饱食 +10 · 心情 +10'}};
const ITEMS={wheel:{name:'小跑轮',cat:'toy',price:0,desc:'每天跑一跑，快乐多一点'},ball:{name:'彩色小球',cat:'toy',price:45,desc:'追着小球，滚出好心情'},tunnel:{name:'软木隧道',cat:'toy',price:70,desc:'钻来钻去，探索小世界'},bed:{name:'小棉被床',cat:'furniture',price:0,desc:'做一个软绵绵的梦'},softbed:{name:'草莓软垫床',cat:'furniture',price:60,desc:'粉色的梦，也很香甜'},cabinet:{name:'小木柜',cat:'furniture',price:90,desc:'把小小收藏好好收起来'},sofa:{name:'奶油小沙发',cat:'furniture',price:120,desc:'偷一会儿懒也没关系'},plant:{name:'雏菊盆栽',cat:'decor',price:25,desc:'在小窝种一朵春天'},painting:{name:'小花挂画',cat:'decor',price:35,desc:'给墙壁添一点温柔'},rug:{name:'蜜桃地毯',cat:'decor',price:40,desc:'踩上去，像踩着云朵'},water:{name:'饮水壶',cat:'fixed',price:0},bowl:{name:'小食盆',cat:'fixed',price:0}};
const STAT_INFO=[['hunger','饱食度','◔','#e5ba81'],['mood','心情','♡','#dfa9ac'],['energy','体力','ϟ','#b0c29b'],['clean','清洁度','✧','#9cbcc4'],['bond','亲密度','❀','#bcb0cc']];
const TASKS=[{id:'feed',name:'吃一顿好吃的',reward:10},{id:'play',name:'一起玩一会儿',reward:12},{id:'clean',name:'整理温暖小窝',reward:10}];
const defaultDecor=()=>[{id:'water',type:'water',x:17,y:77},{id:'bowl',type:'bowl',x:31,y:91},{id:'wheel',type:'wheel',x:79,y:81},{id:'bed',type:'bed',x:88,y:96}];
const today=()=>{const d=new Date();return `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`};
function newState(type,name){return {version:VERSION,type,name,coins:60,stats:{hunger:72,mood:78,energy:85,clean:82,bond:10},inventory:{seed:5,carrot:2,apple:1,cookie:1},owned:['wheel','bed'],decor:defaultDecor(),gameMinutes:8*60,lastSaved:Date.now(),lastInteract:Date.now(),rewardTimes:{},daily:{date:today(),tasks:[],careCoins:0},sound:false,reduced:false,position:{x:51,y:86},sleeping:false,milestones:[]};}
let state=null,action='idle',decorating=false,currentCat='food',toastTimer,bubbleTimer,actionToken=0,route=[],arrival=null,moveTime=0,drag=null,undoDecor=null,audioCtx=null,lastFrame=performance.now(),statsClock=0,soundClock=0;
const pet=$('#hamster'),room=$('#room');
function hamsterSVG(type='cream',face='normal'){
 const t=TYPES[type]||TYPES.cream,smile=face==='sad'?'M55 78 Q60 74 65 78':'M54 74 Q60 80 66 74';
 return `<svg viewBox="0 0 120 130" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="圆滚滚的小仓鼠"><defs><linearGradient id="fur-${type}" x2="0" y2="1"><stop stop-color="${t.light}"/><stop offset="1" stop-color="${t.fur}"/></linearGradient></defs><ellipse cx="60" cy="86" rx="39" ry="37" fill="${t.fur}" stroke="#b08d6c" stroke-width="1.3"/><ellipse cx="32" cy="32" rx="15" ry="16" fill="${t.fur}" stroke="#b08d6c" stroke-width="1.3"/><ellipse cx="88" cy="32" rx="15" ry="16" fill="${t.fur}" stroke="#b08d6c" stroke-width="1.3"/><ellipse cx="32" cy="32" rx="9" ry="10" fill="${t.ear}"/><ellipse cx="88" cy="32" rx="9" ry="10" fill="${t.ear}"/><path d="M22 65 Q19 30 60 29 Q102 30 98 65 Q108 95 60 101 Q12 95 22 65" fill="url(#fur-${type})" stroke="#b08d6c" stroke-width="1.3"/><path d="M42 31 Q60 25 77 32 Q68 40 60 40 Q51 38 42 31" fill="${t.fur}" opacity=".6"/><ellipse cx="60" cy="98" rx="26" ry="22" fill="${t.light}"/><ellipse cx="33" cy="73" rx="12" ry="9" fill="${t.light}"/><ellipse cx="87" cy="73" rx="12" ry="9" fill="${t.light}"/><g class="open-eye"><ellipse cx="42" cy="61" rx="4.7" ry="5.5" fill="#514235"/><ellipse cx="78" cy="61" rx="4.7" ry="5.5" fill="#514235"/><circle cx="43" cy="59" r="1.5" fill="white"/><circle cx="79" cy="59" r="1.5" fill="white"/></g><g class="closed-eye" fill="none" stroke="#6a5242" stroke-width="2.4" stroke-linecap="round"><path d="M37 63 Q42 59 47 63"/><path d="M73 63 Q78 59 83 63"/></g><ellipse cx="33" cy="73" rx="7" ry="4" fill="#e6a69e" opacity=".7"/><ellipse cx="87" cy="73" rx="7" ry="4" fill="#e6a69e" opacity=".7"/><path d="M56 69 Q60 65 64 69 Q60 74 56 69" fill="#cb9282"/><path d="${smile}" fill="none" stroke="#785b49" stroke-width="1.5" stroke-linecap="round"/><g stroke="#8d7361" stroke-width="1" opacity=".6"><path d="M28 75 L13 71 M28 79 L12 81 M92 75 L107 71 M92 79 L108 81"/></g><ellipse cx="37" cy="97" rx="7" ry="10" fill="${t.light}" transform="rotate(-25 37 97)"/><ellipse cx="83" cy="97" rx="7" ry="10" fill="${t.light}" transform="rotate(25 83 97)"/><ellipse cx="43" cy="120" rx="12" ry="6" fill="${t.ear}" stroke="#b08d6c" stroke-width="1"/><ellipse cx="77" cy="120" rx="12" ry="6" fill="${t.ear}" stroke="#b08d6c" stroke-width="1"/></svg>`;
}
function objectSVG(type){
 const head='<svg viewBox="0 0 120 120" xmlns="http://www.w3.org/2000/svg" aria-hidden="true">',end='</svg>';
 const svg={
 water:'<rect x="46" y="99" width="47" height="7" rx="3" fill="#b6a084"/><path d="M78 102 V17" stroke="#a98e6a" stroke-width="6"/><rect x="33" y="15" width="43" height="68" rx="13" fill="#eaf0df" stroke="#a6b6a0" stroke-width="3"/><path d="M37 44 H72 V70 Q72 79 60 79 H48 Q37 79 37 67Z" fill="#b8d3d2"/><rect x="37" y="9" width="35" height="14" rx="5" fill="#abc0a0"/><path d="M54 83 V95 L44 104" fill="none" stroke="#a8aca4" stroke-width="5" stroke-linecap="round"/><path d="M42 29 V62" stroke="white" stroke-width="4" opacity=".7" stroke-linecap="round"/>',
 bowl:'<ellipse cx="60" cy="105" rx="48" ry="8" fill="#ad997733"/><path d="M17 86 Q15 116 60 114 Q105 116 103 86" fill="#d6ab83" stroke="#b38a62" stroke-width="2"/><ellipse cx="60" cy="86" rx="43" ry="14" fill="#eed6b2" stroke="#b38a62" stroke-width="2"/><ellipse cx="60" cy="88" rx="31" ry="8" fill="#b08a58"/><path d="M42 85l8 4m12-6l8 4m-14 5l8 1" stroke="#f5d99e" stroke-width="4" stroke-linecap="round"/><path d="M47 104 Q60 109 74 104" fill="none" stroke="#f3d7bc" stroke-width="2"/>',
 wheel:'<path d="M48 81 L34 116 H87 L73 81" fill="#bca287" stroke="#a58c72" stroke-width="2"/><circle cx="60" cy="58" r="47" fill="#e1caa8" stroke="#b09570" stroke-width="6"/><circle cx="60" cy="58" r="37" fill="#d0d8b4" stroke="#bdc39f" stroke-width="3"/><g class="wheel-spokes" stroke="#eff1d8" stroke-width="3"><path d="M60 21 V95 M23 58 H97 M34 32 L86 84 M34 84 L86 32"/></g><circle cx="60" cy="58" r="9" fill="#b39875"/><circle cx="60" cy="58" r="4" fill="#e9d7b6"/>',
 bed:'<ellipse cx="60" cy="109" rx="55" ry="8" fill="#94785522"/><rect x="10" y="62" width="100" height="48" rx="12" fill="#c39b74" stroke="#aa815e" stroke-width="2"/><rect x="17" y="48" width="86" height="49" rx="13" fill="#f0d4bd" stroke="#d8b395" stroke-width="2"/><rect x="21" y="49" width="37" height="22" rx="8" fill="#fff2dc"/><path d="M23 72 H104 V91 Q103 98 95 98 H25Z" fill="#c4cda9"/><path d="M26 80 H100 M26 89 H100" stroke="#e8edd4" stroke-width="2" stroke-dasharray="7 5"/><rect x="13" y="105" width="10" height="11" rx="3" fill="#a7805d"/><rect x="98" y="105" width="10" height="11" rx="3" fill="#a7805d"/>',
 softbed:'<ellipse cx="60" cy="103" rx="53" ry="16" fill="#cb9f98"/><ellipse cx="60" cy="91" rx="53" ry="20" fill="#e6b6ad" stroke="#bf928a" stroke-width="2"/><ellipse cx="60" cy="87" rx="39" ry="12" fill="#f6d4c6"/><path d="M20 93l5 3m17-1l4 3m23-3l3 4m23-8l4 3" stroke="#ffe8d7" stroke-width="3" stroke-linecap="round"/>',
 ball:'<circle cx="60" cy="79" r="34" fill="#c5d1ba" stroke="#a2b297" stroke-width="2"/><path d="M60 45 Q26 79 60 113 Q94 79 60 45" fill="#edc6b1" stroke="#b1b594" stroke-width="2"/><path d="M27 74 Q60 58 93 74 M29 91 Q60 79 91 91" fill="none" stroke="#fbefd3" stroke-width="4"/><ellipse cx="48" cy="61" rx="8" ry="5" fill="#fff9" transform="rotate(-35 48 61)"/>',
 tunnel:'<path d="M20 108 V75 Q20 36 57 36 L106 56 V108Z" fill="#d7b18a" stroke="#b38c65" stroke-width="3"/><path d="M20 108 V75 Q20 36 57 36 Q91 38 91 76 V108Z" fill="#c5986b" stroke="#b38c65" stroke-width="3"/><path d="M31 108 V77 Q32 53 56 53 Q79 54 79 78 V108" fill="#96765d"/><path d="M62 39 L109 59 M84 54 L110 65 M91 74 L110 78 M94 96 L110 96" stroke="#ecd1af" stroke-width="3"/>',
 cabinet:'<rect x="22" y="30" width="78" height="80" rx="5" fill="#c9a477" stroke="#aa8459" stroke-width="2"/><rect x="29" y="38" width="64" height="29" rx="2" fill="#d9b989"/><rect x="29" y="73" width="64" height="29" rx="2" fill="#d9b989"/><circle cx="61" cy="52" r="3" fill="#a78257"/><circle cx="61" cy="87" r="3" fill="#a78257"/><path d="M30 110 V117 M92 110 V117" stroke="#a78257" stroke-width="7"/><rect x="18" y="24" width="86" height="9" rx="3" fill="#dfc398"/>',
 sofa:'<rect x="15" y="45" width="92" height="54" rx="20" fill="#d5c3a0" stroke="#b7a17f" stroke-width="2"/><rect x="24" y="71" width="73" height="34" rx="8" fill="#e9d9b8"/><rect x="8" y="66" width="22" height="40" rx="9" fill="#dac9a8"/><rect x="90" y="66" width="22" height="40" rx="9" fill="#dac9a8"/><path d="M23 105 V116 M97 105 V116" stroke="#a68d6b" stroke-width="7"/><path d="M61 49 V70 M61 77 V98" stroke="#c3b08d" stroke-width="2"/>',
 plant:'<path d="M62 89 V35" stroke="#91a176" stroke-width="4"/><ellipse cx="46" cy="63" rx="17" ry="8" fill="#a2b483" transform="rotate(30 46 63)"/><ellipse cx="78" cy="52" rx="17" ry="8" fill="#a2b483" transform="rotate(-30 78 52)"/><g fill="#fff5db"><ellipse cx="62" cy="26" rx="7" ry="15"/><ellipse cx="62" cy="26" rx="7" ry="15" transform="rotate(60 62 26)"/><ellipse cx="62" cy="26" rx="7" ry="15" transform="rotate(120 62 26)"/></g><circle cx="62" cy="26" r="7" fill="#d9b567"/><path d="M36 82 H88 L81 114 H44Z" fill="#d4a08a" stroke="#b78973" stroke-width="2"/><rect x="32" y="78" width="60" height="9" rx="3" fill="#dfb29a"/>',
 painting:'<rect x="18" y="14" width="85" height="91" rx="4" fill="#c6a77c"/><rect x="25" y="21" width="71" height="77" fill="#f5ecd6"/><path d="M60 85 V57 M60 77 Q42 69 42 61 M60 70 Q77 63 79 54" fill="none" stroke="#9dac84" stroke-width="3"/><g fill="#dfa99f"><ellipse cx="60" cy="46" rx="10" ry="19"/><ellipse cx="60" cy="46" rx="10" ry="19" transform="rotate(60 60 46)"/><ellipse cx="60" cy="46" rx="10" ry="19" transform="rotate(120 60 46)"/></g><circle cx="60" cy="46" r="8" fill="#e4c77f"/>',
 rug:'<ellipse cx="60" cy="83" rx="55" ry="24" fill="#e7bfae" stroke="#ca9e8a" stroke-width="2"/><ellipse cx="60" cy="83" rx="42" ry="15" fill="none" stroke="#ffe4ce" stroke-width="3"/><path d="M5 80l-4-2m5 10l-4 2m115-10l4-2m-5 10l4 2" stroke="#d9af9b" stroke-width="4"/>'};
 return head+(svg[type]||svg.plant)+end;
}
function notify(text){$('#toast').textContent=text;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200)}
function bubble(text,ms=2800){$('#bubble').textContent=text;$('#bubble').classList.add('visible');clearTimeout(bubbleTimer);bubbleTimer=setTimeout(()=>$('#bubble').classList.remove('visible'),ms);positionPet()}
function hearts(symbol='♡'){for(let i=0;i<5;i++){let p=document.createElement('span');p.className='particle'+(symbol==='✦'?' spark':'');p.textContent=symbol;p.style.left=(state.position.x-5+Math.random()*10)+'%';p.style.top=(state.position.y-14-Math.random()*9)+'%';p.style.animationDelay=i*.08+'s';$('#particles').append(p);setTimeout(()=>p.remove(),2100)}}
function setAction(next){action=next;pet.className='hamster '+(next==='idle'?'':next);updateMood()}
function sound(kind='happy'){
 if(!state?.sound)return;
 try{audioCtx=audioCtx||new (window.AudioContext||window.webkitAudioContext)();if(audioCtx.state==='suspended')audioCtx.resume();const pitches=kind==='coin'?[659,880,1046]:kind==='sleep'?[392,330]:kind==='water'?[700,980,800]:[523,659];pitches.forEach((f,i)=>{let o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.1;o.type='sine';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.035,t+.012);g.gain.exponentialRampToValueAtTime(.001,t+.35);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.4)})}catch(e){state.sound=false;updateSound();notify('这个浏览器暂时不支持声音，仍可正常玩耍。')}
}
function updateSound(){$('#soundButton').classList.toggle('active',!!state?.sound);$('#soundButton').setAttribute('aria-label',state?.sound?'关闭声音':'开启声音');$('#soundButton').title=state?.sound?'关闭声音':'开启声音'}
function save(){if(!state)return;state.lastSaved=Date.now();try{localStorage.setItem(KEY,JSON.stringify(state));$('#saveStatus').textContent='♡ 已自动保存 · '+new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}catch(e){$('#saveStatus').textContent='此浏览器无法自动保存，请在设置中导出存档'}}
function validate(raw){
 if(!raw||raw.version!==VERSION||!TYPES[raw.type]||typeof raw.name!=='string'||!raw.name.trim()||!raw.stats||!Array.isArray(raw.decor)||!Array.isArray(raw.owned))throw Error('存档格式不正确');
 const s=newState(raw.type,raw.name.trim().slice(0,12));const num=(v,d,min=0,max=100)=>Number.isFinite(v)?clamp(v,min,max):d;
 s.coins=Math.floor(num(raw.coins,60,0,999999));for(const [k] of STAT_INFO)s.stats[k]=num(raw.stats[k],s.stats[k]);
 for(const k in FOODS)s.inventory[k]=Math.floor(num(raw.inventory?.[k],0,0,9999));
 s.owned=[...new Set(['wheel','bed',...raw.owned.filter(k=>ITEMS[k]&&ITEMS[k].cat!=='fixed')])];
 s.decor=raw.decor.filter(d=>d&&ITEMS[d.type]&&typeof d.id==='string'&&(ITEMS[d.type].cat==='fixed'||s.owned.includes(d.type))).slice(0,20).map(d=>({id:d.type,type:d.type,x:num(d.x,50,8,92),y:num(d.y,88,d.type==='painting'?30:74,d.type==='painting'?59:96)}));
 s.decor=s.decor.filter((d,i,a)=>a.findIndex(x=>x.type===d.type)===i);for(const t of ['water','bowl'])if(!s.decor.some(d=>d.type===t))s.decor.push(defaultDecor().find(d=>d.type===t));
 s.position={x:num(raw.position?.x,51,8,92),y:num(raw.position?.y,86,68,94)};s.gameMinutes=num(raw.gameMinutes,480,0,1440);s.lastSaved=num(raw.lastSaved,Date.now(),0,Date.now());s.lastInteract=num(raw.lastInteract,Date.now(),0,Date.now());s.sleeping=!!raw.sleeping;s.sound=!!raw.sound;s.reduced=!!raw.reduced;
 if(raw.daily?.date===today()){s.daily.tasks=Array.isArray(raw.daily.tasks)?raw.daily.tasks.filter(k=>TASKS.some(t=>t.id===k)):[];s.daily.careCoins=num(raw.daily.careCoins,0,0,100)}
 else s.daily.date=raw.daily?.date||'';
 for(const k of ['feed','water','pet','play','clean'])s.rewardTimes[k]=num(raw.rewardTimes?.[k],0,0,Date.now());
 s.milestones=Array.isArray(raw.milestones)?raw.milestones.filter(n=>[20,40,60,80,100].includes(n)):[];return s;
}
function resetDaily(){if(state.daily.date!==today()){state.daily={date:today(),tasks:[],careCoins:0};state.coins+=20;state.inventory.seed+=5;notify('新的一天！收到了 20 金币和 5 份瓜子。');return true}return false}
function decay(minutes){minutes=clamp(minutes,0,120);const s=state.stats;s.hunger=clamp(s.hunger-.5*minutes);s.clean=clamp(s.clean-.2*minutes);s.mood=clamp(s.mood-(.3+(s.hunger<25?.35:0)+(s.clean<25?.25:0))*minutes);s.energy=clamp(s.energy+(state.sleeping?12:-.2)*minutes);state.gameMinutes=(state.gameMinutes+minutes*60)%1440}
function statsChanged(){for(const [k] of STAT_INFO)state.stats[k]=clamp(state.stats[k]);checkMilestones();renderHUD();save()}
function checkMilestones(){for(const n of [20,40,60,80,100])if(state.stats.bond>=n&&!state.milestones.includes(n)){state.milestones.push(n);state.coins+=15;notify(`亲密度达到 ${n}！收到 15 金币，小伙伴更喜欢你了。`);hearts('❀')}}
function reward(kind,valid=true){resetDaily();let gain=0;const now=Date.now(),amount={feed:2,water:1,pet:1,play:3,clean:4}[kind]||0;if(valid&&now-(state.rewardTimes[kind]||0)>=120000&&state.daily.careCoins<100){gain=Math.min(amount,100-state.daily.careCoins);state.daily.careCoins+=gain;state.rewardTimes[kind]=now}const task=TASKS.find(t=>t.id===kind);if(valid&&task&&!state.daily.tasks.includes(kind)){state.daily.tasks.push(kind);gain+=task.reward}if(gain){state.coins+=gain;notify(`温柔的照顾被记住了 · +${gain} 金币`);sound('coin')}state.lastInteract=now;statsChanged()}
function mood(){if(state.sleeping)return ['睡觉','做着甜甜的梦'];if(action==='eating')return ['吃东西','认真吃饭中'];if(action==='playing')return ['玩耍','快乐运动中'];if(action==='walking')return ['移动','哒哒哒，走过去'];if(action==='drinking')return ['喝水','咕噜咕噜'];if(action==='petted')return ['开心','被温柔摸摸啦'];if(state.stats.energy<20)return ['困','有一点困啦'];if(state.stats.hunger<25)return ['饿','小肚子饿了'];if(state.stats.mood<25)return ['生气','需要一点安慰'];if(Date.now()-state.lastInteract>180000&&state.stats.mood<60)return ['无聊','想和你一起玩'];return state.stats.mood>70?['开心','今天也很开心']:['普通','安静地陪着你']}
function updateMood(){if(!state)return;const [kind,text]=mood();$('#moodText').textContent=text;pet.setAttribute('aria-label',`抚摸${state.name}，当前${kind}`);const sad=['饿','困','生气','无聊'].includes(kind);if(pet.dataset.face!==String(sad)){pet.dataset.face=String(sad);$('#hamsterArt').innerHTML=hamsterSVG(state.type,sad?'sad':'normal')}}
function renderHUD(){if(!state)return;$('#coins').textContent=state.coins;$('#petName').textContent=state.name;$('#roomName').replaceChildren(document.createTextNode(state.name+'的温暖小窝 '));const star=document.createElement('span');star.textContent='✧';$('#roomName').append(star);for(const [key] of STAT_INFO){const v=Math.round(state.stats[key]);$(`#stat-${key} .stat-fill`).style.width=v+'%';$(`#stat-${key} b`).textContent=v+'/100';$(`#stat-${key} .stat-track`).setAttribute('aria-valuenow',v)}$('#bondNote').textContent=state.stats.bond>=80?'它开始主动靠近你，因为这里是家。':state.stats.bond>=40?'熟悉的陪伴，让它安心又快乐。':'一点点照顾，都会被记住。';$('#tasks').innerHTML=TASKS.map(t=>`<div class="task ${state.daily.tasks.includes(t.id)?'done':''}"><span class="task-check">${state.daily.tasks.includes(t.id)?'✓':''}</span><span class="task-name">${t.name}</span><span class="task-reward">${state.daily.tasks.includes(t.id)?'已完成':'✦ '+t.reward}</span></div>`).join('');const night=state.gameMinutes<360||state.gameMinutes>=1140;room.classList.toggle('night',night);const hour=Math.floor(state.gameMinutes/60);$('#clock').textContent=(night?'☾ 夜晚':'☀ '+(hour<12?'早上好':'午后时光'))+' · '+String(hour).padStart(2,'0')+':'+String(Math.floor(state.gameMinutes%60)).padStart(2,'0');$('#roomStatus').textContent=night?'月光轻轻的，晚安也要甜甜的':state.stats.clean<35?'小窝有点乱，整理一下吧':'阳光刚刚好，陪它玩一会儿吧';updateMood();renderDirt()}
function renderDirt(){const count=Math.floor((100-state.stats.clean)/12),layer=$('#dirtLayer');if(Number(layer.dataset.count)===count)return;layer.dataset.count=count;layer.innerHTML='';for(let i=0;i<count;i++){let d=document.createElement('span');d.className='dirt';d.textContent=['⌁','◌','✦','•'][i%4];d.style.left=(12+(i*23)%77)+'%';d.style.top=(74+(i*7)%19)+'%';layer.append(d)}}
function renderFurniture(){const holder=$('#furniture');holder.innerHTML='';state.decor.forEach(d=>{let b=document.createElement('button');b.className='furniture '+d.type;b.dataset.id=d.id;b.dataset.type=d.type;b.style.left=d.x+'%';b.style.top=d.y+'%';b.style.zIndex=d.type==='rug'?2:Math.round(d.y);if(d.type==='painting')b.style.height='22%';b.setAttribute('aria-label',ITEMS[d.type].name);b.innerHTML=objectSVG(d.type)+`<span class="object-label">${ITEMS[d.type].name}</span>`;b.addEventListener('click',()=>{if(b.dataset.dragged==='yes'){b.dataset.dragged='';return}if(decorating){if(ITEMS[d.type].cat==='fixed')return notify('食盆和水壶可以移动，需要留在小窝里。');showRemove(d)}else interactObject(d.type)});b.addEventListener('pointerdown',e=>startDrag(e,d,b));holder.append(b)})}
function positionPet(){if(!state)return;pet.style.left=state.position.x+'%';pet.style.top=state.position.y+'%';pet.style.zIndex=Math.round(state.position.y)+40;$('#bubble').style.left=clamp(state.position.x,15,85)+'%';$('#bubble').style.top=(state.position.y-25)+'%'}
function obstacle(x,y,ignore){return state.decor.some(d=>d.type!==ignore&&!['painting','rug'].includes(d.type)&&Math.abs(x-d.x)<7&&y>d.y-7&&y<d.y+2)}
function pathTo(target,ignore){const sx=Math.round(state.position.x/4),sy=Math.round((state.position.y-68)/3),gx=Math.round(target.x/4),gy=Math.round((target.y-68)/3);const encode=(x,y)=>x+','+y,queue=[[sx,sy]],prev=new Map([[encode(sx,sy),null]]);let found=null;for(let i=0;i<queue.length;i++){const [x,y]=queue[i];if(x===gx&&y===gy){found=[x,y];break}for(const [dx,dy] of [[1,0],[-1,0],[0,1],[0,-1]]){const nx=x+dx,ny=y+dy,k=encode(nx,ny);if(nx<2||nx>23||ny<0||ny>9||prev.has(k)||obstacle(nx*4,68+ny*3,ignore))continue;prev.set(k,[x,y]);queue.push([nx,ny])}}if(!found)return null;const points=[];for(let p=found;prev.get(encode(...p));p=prev.get(encode(...p)))points.unshift({x:p[0]*4,y:68+p[1]*3});points.push(target);return points}
function available(){if(decorating){notify('先完成布置，再和小仓鼠互动吧。');return false}if(state.sleeping){showWake();return false}if(action!=='idle'){bubble('等一下下，我马上就好啦');return false}return true}
function go(type,cb){const d=state.decor.find(d=>d.type===type);if(!d){notify('先把'+ITEMS[type].name+'摆进房间吧。');return false}const target={x:clamp(d.x+(d.x>60?-9:9),8,92),y:clamp(d.y+1,70,94)};const points=pathTo(target,type);if(!points){notify('这里走不过去，试着移动一下家具。');return false}route=points;arrival=cb;setAction('walking');return true}
function timed(actionName,duration,finish){const token=++actionToken;setAction(actionName);setTimeout(()=>{if(token!==actionToken)return;document.querySelectorAll('.furniture.active').forEach(n=>n.classList.remove('active'));setAction('idle');finish()},duration)}
function openModal(html){$('#modalContent').innerHTML=html;$('#closeModal').hidden=false;if(!$('#modal').open)$('#modal').showModal()}
function closeModal(){if($('#closeModal').hidden)return;$('#modal').close()}
function adopt(){let choice='cream';openModal(`<div class="eyebrow">WELCOME TO YOUR LITTLE HOME</div><h2 class="modal-title" style="margin-top:9px">遇见你的小小伙伴</h2><p class="modal-intro">选一只喜欢的小仓鼠，给它一个名字。<br>从今天起，一起把普通的日子过得暖暖的。</p><div class="choose-grid">${Object.entries(TYPES).map(([id,t])=>`<button class="choose-card ${id==='cream'?'selected':''}" data-type="${id}" aria-pressed="${id==='cream'}">${hamsterSVG(id)}<b>${t.name}</b><small>${t.desc}</small></button>`).join('')}</div><label class="name-label" for="nameInput">你想叫它什么名字？</label><input type="text" id="nameInput" maxlength="12" value="小布丁" autocomplete="off"><button class="primary-button start-button" id="adoptButton">带它回家 ♡</button><div class="modal-footer">准备好了 60 金币和一篮食物，欢迎回家。</div>`);$('#closeModal').hidden=true;document.querySelectorAll('.choose-card').forEach(b=>b.onclick=()=>{choice=b.dataset.type;document.querySelectorAll('.choose-card').forEach(c=>{c.classList.toggle('selected',c===b);c.setAttribute('aria-pressed',c===b)})});$('#adoptButton').onclick=()=>{const name=$('#nameInput').value.trim();if(!name){notify('给小伙伴起个名字吧。');$('#nameInput').focus();return}state=newState(choice,name);$('#modal').close();initPet();save();bubble('你好呀，我终于有家啦！',4500);sound()};$('#nameInput').onkeydown=e=>{if(e.key==='Enter')$('#adoptButton').click()}}
function initPet(){$('#portrait').innerHTML=hamsterSVG(state.type);pet.dataset.face='';document.body.classList.toggle('reduced-motion',state.reduced);renderFurniture();renderHUD();positionPet();updateSound();setAction(state.sleeping?'sleeping':'idle')}
function showFood(){if(!available())return;openModal(`<h2 class="modal-title">今天吃点什么？</h2><p class="modal-intro">抱着小零食，快乐就是这么简单。饱食度太高时，让它休息一下。</p><div class="catalog-grid">${Object.entries(FOODS).map(([id,f])=>`<div class="item-card"><div class="item-art">${f.icon}</div><h3>${f.name}</h3><p>${f.desc}</p><small>剩余 ${state.inventory[id]} 份</small><button data-food="${id}" ${!state.inventory[id]?'disabled':''}>喂一份</button></div>`).join('')}</div><button class="soft-button" id="foodShop" style="margin-top:18px">食物不够？逛逛商店 ↗</button>`);document.querySelectorAll('[data-food]').forEach(b=>b.onclick=()=>feed(b.dataset.food));$('#foodShop').onclick=()=>showShop('food')}
function feed(id){if(state.stats.hunger>94){notify('小肚子已经饱啦，晚一点再吃吧。');return}if(!state.inventory[id]||action!=='idle'||state.sleeping)return;closeModal();const food=FOODS[id];if(go('bowl',()=>{state.inventory[id]--;save();$('#foodProp').textContent=food.icon;bubble('啊呜啊呜，好好吃！');sound();timed('eating',3500,()=>{state.stats.hunger+=food.hunger;state.stats.mood+=food.mood;state.stats.clean-=2;state.stats.bond+=1.5;reward('feed');hearts()})}))bubble('闻到好吃的啦！')}
function water(){if(!available())return;go('water',()=>{bubble('咕噜咕噜，清凉一下');sound('water');timed('drinking',2500,()=>{const useful=state.stats.energy<95||state.stats.mood<95;state.stats.energy+=3;state.stats.mood+=2;state.stats.bond+=.5;reward('water',useful);hearts('✧')})})}
function pat(){if(!available())return;bubble(state.stats.bond>=60?'最喜欢你啦！再贴贴♡':'摸摸头，心里暖暖的');hearts();sound();timed('petted',1800,()=>{const useful=state.stats.mood<95;state.stats.mood+=7;state.stats.bond+=2;reward('pet',useful)})}
function showPlay(){if(!available())return;openModal(`<h2 class="modal-title">一起玩一会儿吧</h2><p class="modal-intro">玩耍消耗 8 点体力，恢复 12 点心情。开心也要记得休息。</p><div class="catalog-grid">${['wheel','ball','tunnel'].map(k=>`<div class="item-card"><div class="item-art">${objectSVG(k)}</div><h3>${ITEMS[k].name}</h3><p>${ITEMS[k].desc}</p><button data-play="${k}" ${!state.decor.some(d=>d.type===k)?'disabled':''}>${state.decor.some(d=>d.type===k)?'一起玩':state.owned.includes(k)?'先摆放到房间':'商店可购买'}</button></div>`).join('')}</div>`);document.querySelectorAll('[data-play]').forEach(b=>b.onclick=()=>play(b.dataset.play))}
function play(type){if(state.stats.energy<15){notify('有点累了，先睡个小觉吧。');return}if(action!=='idle'||state.sleeping)return;closeModal();go(type,()=>{const obj=$(`.furniture[data-type="${type}"]`);obj?.classList.add('active');bubble(type==='wheel'?'跑起来，快乐转圈圈！':type==='tunnel'?'探险开始！里面有小秘密吗？':'滚呀滚，追到你啦！');sound();timed('playing',6500,()=>{state.stats.energy-=8;state.stats.hunger-=3;state.stats.clean-=2;state.stats.mood+=12;state.stats.bond+=2;reward('play');hearts('✦')})})}
function sleep(){if(!available())return;const type=state.decor.some(d=>d.type==='softbed')?'softbed':'bed';if(!state.decor.some(d=>d.type===type)){notify('先从物品箱摆放一张小床吧。');return}go(type,()=>{state.sleeping=true;setAction('sleeping');bubble('晚安，梦里也有小瓜子……',4000);sound('sleep');save()})}
function showWake(){openModal(`<h2 class="modal-title">小伙伴正在做梦</h2><div class="large-emoji">☾</div><p class="modal-intro">睡眠每分钟恢复 12 点体力。现在体力 ${Math.round(state.stats.energy)}/100。<br>想叫醒它，还是让它再睡一会儿？</p><div class="notice-button-row"><button id="keepSleep">继续睡</button><button class="primary-button" id="wakeButton">轻轻叫醒</button></div>`);$('#keepSleep').onclick=closeModal;$('#wakeButton').onclick=()=>{state.sleeping=false;actionToken++;setAction('idle');closeModal();bubble('睡醒啦，今天也喜欢你！');save()}}
function clean(){if(!available())return;if(state.stats.clean>=97){bubble('小窝已经干干净净啦！');return}const useful=state.stats.clean<90;bubble('一起把小窝变香香');timed('cleaning',2000,()=>{state.stats.clean=100;state.stats.mood+=5;state.stats.bond+=1;reward('clean',useful);hearts('✧');bubble('干净的小窝，心情也亮起来了')})}
function interactObject(type){if(['wheel','ball','tunnel'].includes(type)){if(available())play(type)}else if(type==='water')water();else if(type==='bowl')showFood();else if(['bed','softbed'].includes(type))sleep();else bubble('这个小角落，我很喜欢。')}
function showShop(cat='food'){currentCat=cat;openModal(`<div class="eyebrow">LITTLE THINGS, BIG HAPPINESS</div><h2 class="modal-title" style="margin-top:8px">小窝杂货铺 <small style="font-size:13px;color:#b29a61">✦ ${state.coins}</small></h2><p class="modal-intro">选一点喜欢的，把小日子装扮得更可爱。</p><div class="catalog-tabs">${[['food','食物'],['toy','玩具'],['furniture','家具'],['decor','装饰'],['storage','物品箱']].map(([k,n])=>`<button data-cat="${k}" class="${k===cat?'selected':''}">${n}</button>`).join('')}</div><div class="catalog-grid" id="shopGrid"></div>`);document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>showShop(b.dataset.cat));renderShop(cat)}
function renderShop(cat){const list=cat==='food'?Object.entries(FOODS):Object.entries(ITEMS).filter(([k,v])=>cat==='storage'?state.owned.includes(k):v.cat===cat&&v.price>0);$('#shopGrid').innerHTML=list.map(([id,f])=>{const owned=state.owned.includes(id),placed=state.decor.some(d=>d.type===id);let text=cat==='storage'?(placed?'已经摆放':'摆放到小窝'):owned?'已拥有':`✦ ${f.price} · 购买`;return `<div class="item-card"><div class="item-art">${cat==='food'?f.icon:objectSVG(id)}</div><h3>${f.name}</h3><p>${f.desc}</p>${cat==='food'?`<small>库存 ${state.inventory[id]} 份</small>`:''}<button data-buy="${id}" ${(cat==='storage'?placed:owned||state.coins<f.price)?'disabled':''}>${text}</button></div>`}).join('')||'<p class="text-note">物品箱暂时空空的，逛一逛小商店吧。</p>';document.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>cat==='storage'?placeItem(b.dataset.buy):buy(b.dataset.buy))}
function buy(id){const item=FOODS[id]||ITEMS[id];if(!item||state.coins<item.price)return;if(ITEMS[id]&&state.owned.includes(id))return;state.coins-=item.price;if(FOODS[id])state.inventory[id]++;else state.owned.push(id);sound('coin');notify('买到'+item.name+'啦'+(ITEMS[id]?'，可以在物品箱摆放。':'！'));renderHUD();save();showShop(currentCat)}
function placeItem(type){if(action!=='idle'||state.sleeping){notify('等仓鼠醒来或完成动作，再布置吧。');return}if(state.decor.some(d=>d.type===type)||!state.owned.includes(type))return;const d={id:type,type,x:50,y:type==='painting'?46:92};let spot=null;for(const y of (type==='painting'?[45]:[94,82,74]))for(const x of [50,40,65,20,88,10]){d.x=x;d.y=y;if(validPlacement(d)){spot={...d};break}if(spot)break}if(!spot){notify('地面有点拥挤，先收回一件家具吧。');return}undoDecor=JSON.stringify(state.decor);state.decor.push(spot);closeModal();decorating=true;room.classList.add('decorating');$('#decorBanner').hidden=false;$('#decorateButton').textContent='＋ 添加 / 物品箱';renderFurniture();save();notify('拖动新家具，给它找个舒服的位置吧。')}
function toggleDecor(){if(decorating){showShop('storage');return}if(!available())return;decorating=true;undoDecor=JSON.stringify(state.decor);room.classList.add('decorating');$('#decorBanner').hidden=false;$('#decorateButton').textContent='＋ 添加 / 物品箱';notify('拖动家具调整位置，点击家具可收回。')}
function finishDecor(){decorating=false;drag=null;room.classList.remove('decorating');$('#decorBanner').hidden=true;$('#decorateButton').textContent='⌂ 布置小窝';renderFurniture();save();bubble('小窝变得更温暖啦！')}
function validPlacement(d){if(d.type==='painting')return d.y>=30&&d.y<=59;if(d.y<74||d.y>96||d.x<8||d.x>92)return false;if(d.type==='rug')return true;return !state.decor.some(o=>o.id!==d.id&&!['painting','rug'].includes(o.type)&&Math.abs(o.x-d.x)<13&&Math.abs(o.y-d.y)<10)}
function startDrag(e,d,b){if(!decorating)return;e.preventDefault();b.setPointerCapture(e.pointerId);drag={d,b,start:{x:d.x,y:d.y},client:{x:e.clientX,y:e.clientY},moved:false};b.classList.add('dragging');b.onpointermove=ev=>{if(!drag)return;const r=room.getBoundingClientRect();if(Math.hypot(ev.clientX-drag.client.x,ev.clientY-drag.client.y)>5)drag.moved=true;d.x=clamp((ev.clientX-r.left)/r.width*100,8,92);d.y=clamp((ev.clientY-r.top)/r.height*100,d.type==='painting'?30:74,d.type==='painting'?59:96);b.style.left=d.x+'%';b.style.top=d.y+'%';b.style.outlineColor=validPlacement(d)?'#8c9f6d':'#c5786f'};const end=()=>{if(!drag)return;const moved=drag.moved;const original=drag.start;if(!validPlacement(d)){d.x=original.x;d.y=original.y;notify('家具不能挤在一起，换个位置吧。')}else if(moved){undoDecor=JSON.stringify(state.decor.map(o=>o.id===d.id?{...o,...original}:o));save()}b.style.left=d.x+'%';b.style.top=d.y+'%';b.classList.remove('dragging');b.dataset.dragged=moved?'yes':'';drag=null;b.onpointermove=null;b.onpointerup=null;b.onpointercancel=null};b.onpointerup=end;b.onpointercancel=end}
function showRemove(d){openModal(`<h2 class="modal-title">${ITEMS[d.type].name}</h2><div class="item-art" style="height:110px">${objectSVG(d.type)}</div><p class="modal-intro">收回后会保留在物品箱，随时都可以重新摆放。</p><div class="notice-button-row"><button id="cancelRemove">留在这里</button><button class="primary-button" id="removeItem">收回物品箱</button></div>`);$('#cancelRemove').onclick=closeModal;$('#removeItem').onclick=()=>{undoDecor=JSON.stringify(state.decor);state.decor=state.decor.filter(o=>o.id!==d.id);renderFurniture();save();closeModal();notify('已经收回物品箱啦。')}}
function settings(){openModal(`<h2 class="modal-title">小窝设置</h2><p class="modal-intro">好好保存这份小小的陪伴。</p><div class="settings-row"><div><b>给小伙伴改名</b><p>新的名字，熟悉的喜欢。</p></div><button id="renameButton">改名字</button></div><div class="settings-row"><div><b>导出 / 导入存档</b><p>换电脑之前，记得带走小伙伴。</p></div><button id="exportSave">导出</button><button id="importSave">导入</button></div><div class="settings-row"><div><b>减少动态效果</b><p>保留互动，减少画面动画。</p></div><button id="reduceButton">${state.reduced?'已开启':'已关闭'}</button></div><div class="settings-row"><div><b>撤销上次布置</b><p>恢复最近一次家具摆放。</p></div><button id="undoButton" ${!undoDecor?'disabled':''}>撤销</button></div><div class="settings-row danger"><div><b>重新收养</b><p>会清除本地进度，建议先导出存档。</p></div><button id="resetButton">重新开始</button></div><p class="text-note">进度保存在当前浏览器。离线最多结算 2 小时，没有死亡或失败惩罚。请勿清理浏览器数据，或提前导出备份。</p>`);$('#renameButton').onclick=rename;$('#exportSave').onclick=exportSave;$('#importSave').onclick=importSave;$('#reduceButton').onclick=()=>{state.reduced=!state.reduced;document.body.classList.toggle('reduced-motion',state.reduced);save();settings()};$('#undoButton').onclick=()=>{if(action!=='idle'||state.sleeping)return notify('等仓鼠休息好，再调整家具。');if(undoDecor){state.decor=JSON.parse(undoDecor);undoDecor=null;renderFurniture();save();notify('已撤销上次布置');settings()}};$('#resetButton').onclick=()=>{openModal('<h2 class="modal-title">重新开始吗？</h2><p class="modal-intro">当前仓鼠和房间进度将被清除。这个操作不能撤销，建议先导出存档。</p><div class="notice-button-row"><button id="cancelReset">保留小窝</button><button class="primary-button" id="confirmReset">确认重新开始</button></div>');$('#cancelReset').onclick=settings;$('#confirmReset').onclick=()=>{actionToken++;route=[];arrival=null;state=null;decorating=false;room.classList.remove('decorating');$('#decorBanner').hidden=true;$('#decorateButton').textContent='⌂ 布置小窝';try{localStorage.removeItem(KEY)}catch(e){}$('#furniture').innerHTML='';$('#hamsterArt').innerHTML='';$('#particles').innerHTML='';$('#dirtLayer').innerHTML='';undoDecor=null;adopt()}}}
function rename(){openModal(`<h2 class="modal-title">一个可爱的名字</h2><label class="name-label" for="renameInput">仓鼠名字（最多 12 个字）</label><input type="text" maxlength="12" id="renameInput" value="${esc(state.name)}"><button class="primary-button start-button" id="saveName">保存名字 ♡</button>`);$('#saveName').onclick=()=>{const n=$('#renameInput').value.trim();if(!n)return notify('名字还没有填好哦。');state.name=n;renderHUD();save();closeModal();notify('你好呀，'+n+'！')}}
function exportSave(){save();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='hamster-save-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);notify('已准备好存档下载。')}
function importSave(){if(action!=='idle'&&action!=='sleeping')return notify('请等小仓鼠完成当前动作，再导入存档。');const input=document.createElement('input');input.type='file';input.accept='.json,application/json';input.onchange=async()=>{const f=input.files[0];if(!f)return;if(f.size>100000)return notify('这个文件太大了，请选择游戏导出的 JSON 存档。');try{const restored=validate(JSON.parse(await f.text()));openModal('<h2 class="modal-title">恢复这个小窝吗？</h2><p class="modal-intro">导入会替换当前进度。建议先导出当前存档。</p><div class="notice-button-row"><button id="cancelImport">取消</button><button class="primary-button" id="confirmImport">确认恢复</button></div>');$('#cancelImport').onclick=settings;$('#confirmImport').onclick=()=>{actionToken++;route=[];arrival=null;decorating=false;room.classList.remove('decorating');$('#decorBanner').hidden=true;$('#decorateButton').textContent='⌂ 布置小窝';undoDecor=null;state=restored;resetDaily();initPet();save();closeModal();notify('欢迎回家，进度恢复成功！')}}catch(e){notify('无法读取这份存档，原来的小窝没有被修改。')}};input.click()}
function frame(now){const dt=Math.min((now-lastFrame)/1000,.1);lastFrame=now;if(state){if(route.length){let target=route[0],dx=target.x-state.position.x,dy=target.y-state.position.y,d=Math.hypot(dx,dy),step=dt*11;if(d<=step){state.position={...target};route.shift()}else{state.position.x+=dx/d*step;state.position.y+=dy/d*step}positionPet();if(!route.length){setAction('idle');const cb=arrival;arrival=null;cb?.()}}statsClock+=dt;soundClock+=dt;if(statsClock>=1){statsClock=0;if(!decorating)decay(1/60);if(state.sleeping&&state.stats.energy>=100){state.sleeping=false;setAction('idle');bubble('充满电啦，想和你玩！');save()}if(resetDaily())save();renderHUD()}if(soundClock>=12){soundClock=0;if(state.sound)sound('sleep')}if(action==='idle'&&!decorating&&now-moveTime>20000){moveTime=now;if(Math.random()<.45){let target={x:clamp(state.position.x+(Math.random()-.5)*20,10,90),y:clamp(state.position.y+(Math.random()-.5)*10,71,94)};const points=pathTo(target);if(points){route=points;arrival=()=>{};setAction('walking')}}}}requestAnimationFrame(frame)}
// All event handlers are registered once; no action can spend or reward twice.
$('#closeModal').onclick=closeModal;$('#modal').addEventListener('cancel',e=>{if($('#closeModal').hidden)e.preventDefault()});$('#modal').addEventListener('click',e=>{if(e.target===$('#modal'))closeModal()});$('#hamster').onclick=()=>state&&pat();$('#soundButton').onclick=()=>{if(!state)return;state.sound=!state.sound;updateSound();if(state.sound)sound();else audioCtx?.suspend();save()};$('#settingsButton').onclick=()=>state&&settings();$('#shopButton').onclick=()=>state&&showShop();$('#coinButton').onclick=()=>state&&showShop();$('#decorateButton').onclick=()=>state&&toggleDecor();$('#finishDecor').onclick=finishDecor;document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(!state)return;({feed:showFood,water,pet:pat,play:showPlay,sleep,clean}[b.dataset.action])()});
$('#stats').innerHTML=STAT_INFO.map(([k,n,icon,color])=>`<div class="stat" id="stat-${k}"><div class="stat-label"><span><i style="color:${color};font-style:normal">${icon}</i>${n}</span><b>0/100</b></div><div class="stat-track" role="progressbar" aria-label="${n}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"><div class="stat-fill" style="background:${color}"></div></div></div>`).join('');
let raw=null;try{raw=localStorage.getItem(KEY)}catch(e){$('#saveStatus').textContent='本地存储不可用，请使用设置中的导出存档'}
if(raw){try{state=validate(JSON.parse(raw));const away=clamp((Date.now()-state.lastSaved)/60000,0,120);decay(away);if(state.sleeping&&state.stats.energy>=100)state.sleeping=false;resetDaily();initPet();save();if(away>2)bubble('你回来啦！我一直在这里等你。',4000)}catch(e){openModal('<h2 class="modal-title">小窝存档需要帮助</h2><p class="modal-intro">旧存档暂时无法读取，已经保留原始数据。你可以先下载备份，再重新收养。</p><div class="notice-button-row"><button id="backupBroken">备份原存档</button><button class="primary-button" id="startFresh">重新收养</button></div>');$('#closeModal').hidden=true;$('#backupBroken').onclick=()=>{const u=URL.createObjectURL(new Blob([raw],{type:'application/json'})),a=document.createElement('a');a.href=u;a.download='hamster-unreadable-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};$('#startFresh').onclick=adopt}}
else adopt();
let hiddenAt=null;document.addEventListener('visibilitychange',()=>{if(document.hidden){hiddenAt=Date.now();save()}else if(state){if(hiddenAt)decay(clamp((Date.now()-hiddenAt)/60000,0,120));hiddenAt=null;lastFrame=performance.now();renderHUD();save()}});window.addEventListener('pagehide',save);setInterval(save,15000);requestAnimationFrame(frame);
})();
